### ISSUE TITLE
"Login Timeout" Issue!

### ISSUE THREAD

**Issue by karanpatel567** [ClearSkyTeam/ClearSky#569]
When my server is up and running i go on my server then it says "login Timout" I am using the latest 0.15x phar php5 please fix this in the new phar or give me advice! Thx reply! This is the phar name "2_DEVsafe_ClearSky-php5-0.15-9d48670b4c7b7295a1020ae06cd81ac40b3aed7b.phar"

**Comment by 2449673842** [comment]
me too

**Comment by robske110** [comment]
Does it work with 1_DEV...

**Comment by karanpatel567** [comment]
Yeah but when i start it up and try to go on my server it says "Building Terrain" then mcpe crashes so yeah i cant do anything!

**Comment by karanpatel567** [comment]
Please fix this and send out a new phar please mak the new phar php5

**Comment by Aericio** [comment]
Use the "SRC" file. Delete old ClearSky.phar and replace with the ClearSky "src" folder

**Comment by karanpatel567** [comment]
I dont get it tho how do I replace the src file with my clearsky phar

**Comment by karanpatel567** [comment]
And I tried that didnt work

**Comment by karanpatel567** [comment]
I just dont get it u want me to delete clearsky phar and replace with SCR file what is that gonna do!

**Comment by daniktheboss** [comment]
The server will run off the src folder... the phar us compiled of the src folder

**Comment by kam187** [comment]
Can confirm this happens to me with latest trunk on php5 branch.

**Comment by robske110** [comment]
CONFIRMED offically now

**Comment by robske110** [comment]
PHP7 doesn't seem to connect at all though

**Comment by thebigsmileXD** [comment]
I can connect, but the motd is not shown client side

**Comment by robske110** [comment]
I'll take a deep look into this later

**Comment by robske110** [comment]
fixed

**Comment by kam187** [comment]
Still not working.  I noticed the fix was not pushed over to php5 (in packet.php) i manually removed the false and still the same:

[21:36:45] [Server thread/INFO]: test[/192.168.1.38:60047] logged out due to Login timeout

**Comment by robske110** [comment]
We discontinued php5 widly, i'll perform some last checks there but please note that php5 is very likely to get no 0.16 support

**Comment by kam187** [comment]
Sure i understand.  I just need php5 for a little bit longer.

**Comment by kam187** [comment]
Appreciate your help.

**Comment by robske110** [comment]
I'll quickly provide you a version where it worked. Until then you can try to just rename the four 0.15.x strings to 0.15

**Comment by kam187** [comment]
ok let me try that

**Comment by kam187** [comment]
Just checked they are all already 0.15 now.  Only this one left:
src/pocketmine/PocketMine.php:	const MINECRAFT_VERSION = "v0.15.x beta";

**Comment by robske110** [comment]
This should not affect it

**Comment by kam187** [comment]
Yeah.  So that's not the issue.

**Comment by robske110** [comment]
Well, i'll just send you a src folder tomorrow wich has a working version, but i can't say if i can provide updates at all

**Comment by kam187** [comment]
How old is it?  Or any hints as to what the problem might be I can look into it?  I use to dev php and pocketmine ages ago.

**Comment by robske110** [comment]
Well i could conpare it to the current src but, sorry this will hapenn tomorrow (I'm already in bed :P)

**Comment by kam187** [comment]
Sure np.

**Comment by kam187** [comment]
Fixed it :)

[22:21:52] [Server thread/CRITICAL]: ClassNotFoundException: "Class pocketmine\event\player\PlayerHungerChangeEvent not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 128

I just commented it out for now.  Will find the function and add it in.

**Comment by kam187** [comment]
FYI there's alot of the newer changes like Hopper.php that still have IntTag StringTag etc in them instead of String.

I guess you have some auto replace tools for that?

**Comment by Aericio** [comment]
I think they do it manually, xd

**Comment by robske110** [comment]
yep, I'll look what i can do for fixing the merge
